name: '<3'
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: "BrowserStack Test on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: "BrowserStack Env Setup"
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME}}
          access_key: ${{ secrets.BROWSERSTACK_ACCESS_KEY}}
      - name: 'BrowserStack Local Tunnel Setup'
        uses: browsterstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
      - name: 'Checkout the repository'
        uses: GianFrancoMoggia/seleniumtest@master
      - name: 'Install the dependencies'
        run: pip install selenium
      - name: 'Running test on BrowserStack'
        run: python main.py
      - name: 'BrowserStackLocal Stop'
        uses: broserstack/github-actions/setup-local@master
        with: 
          local-testing: stop
