name: '<3'
on: [push, pull_request]
jobs:
  ubuntu-job:
    name: "BrowserStack Test on Ubuntu"
    runs-on: ubuntu-latest
    steps:
      - name: "BrowserStack Env Setup"
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY}}
      - name: 'BrowserStack Local Tunnel Setup'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
      - name: "Actions"
        uses: actions/checkout@v2
      - name: 'Instalar las dependencias'
        run: pip install selenium
      - name: 'Prueba de BrowserStack'
        run: python main.py
      - name: 'BrowserStackLocal Stop'
        uses: browserstack/github-actions/setup-local@master
        with: 
          local-testing: stop
